/**
Problem 45: Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

package main

import "testing"

func TestTriPentaHexagonNumber(t *testing.T) {
	type args struct {
		limit int64
	}
	tests := []struct {
		name string
		args args
		want int64
	}{
		{name: "first", args: args{limit: 41000}, want: 40755},
		{name: "next", args: args{limit: 10000000000}, want: 1533776805},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := TriPentaHexagonNumber(tt.args.limit); got != tt.want {
				t.Errorf("TriPentaHexagonNumber() = %v, want %v", got, tt.want)
			}
		})
	}
}
