/**
Problem 44: Pentagon numbers

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

package main

func ClosestPentagonalDistance(limit int) int {
	min_d := limit * limit
	pentagonals := make(map[int]bool)
	for i, p_i := 1, 1; p_i < limit*limit; i, p_i = i+1, pentagonal(i+1) {
		pentagonals[p_i] = true
	}

	for i := 1; i < limit; i++ {
		for j := i + 1; j < limit; j++ {
			p_i, p_j := pentagonal(i), pentagonal(j)
			if pentagonals[p_j-p_i] && pentagonals[p_i+p_j] {
				if min_d > p_j-p_i {
					min_d = p_j - p_i
				}
			}
		}
	}

	return min_d
}

func pentagonal(n int) int {
	return n * (3*n - 1) / 2
}
